/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as MatrixRouteImport } from './routes/matrix/route'
import { Route as AppIndexImport } from './routes/_app.index'
import { Route as MatrixFieldsImport } from './routes/matrix/fields'
import { Route as MatrixDataIndexImport } from './routes/matrix/data.index'
import { Route as MatrixDataDataIdImport } from './routes/matrix/data.$dataId'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const MatrixRouteRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const MatrixFieldsRoute = MatrixFieldsImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => MatrixRouteRoute,
} as any)

const MatrixDataIndexRoute = MatrixDataIndexImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => MatrixRouteRoute,
} as any)

const MatrixDataDataIdRoute = MatrixDataDataIdImport.update({
  id: '/data/$dataId',
  path: '/data/$dataId',
  getParentRoute: () => MatrixRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/matrix/fields': {
      id: '/matrix/fields'
      path: '/fields'
      fullPath: '/matrix/fields'
      preLoaderRoute: typeof MatrixFieldsImport
      parentRoute: typeof MatrixRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/matrix/data/$dataId': {
      id: '/matrix/data/$dataId'
      path: '/data/$dataId'
      fullPath: '/matrix/data/$dataId'
      preLoaderRoute: typeof MatrixDataDataIdImport
      parentRoute: typeof MatrixRouteImport
    }
    '/matrix/data/': {
      id: '/matrix/data/'
      path: '/data'
      fullPath: '/matrix/data'
      preLoaderRoute: typeof MatrixDataIndexImport
      parentRoute: typeof MatrixRouteImport
    }
  }
}

// Create and export the route tree

interface MatrixRouteRouteChildren {
  MatrixFieldsRoute: typeof MatrixFieldsRoute
  MatrixDataDataIdRoute: typeof MatrixDataDataIdRoute
  MatrixDataIndexRoute: typeof MatrixDataIndexRoute
}

const MatrixRouteRouteChildren: MatrixRouteRouteChildren = {
  MatrixFieldsRoute: MatrixFieldsRoute,
  MatrixDataDataIdRoute: MatrixDataDataIdRoute,
  MatrixDataIndexRoute: MatrixDataIndexRoute,
}

const MatrixRouteRouteWithChildren = MatrixRouteRoute._addFileChildren(
  MatrixRouteRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/matrix': typeof MatrixRouteRouteWithChildren
  '': typeof AppRouteWithChildren
  '/matrix/fields': typeof MatrixFieldsRoute
  '/': typeof AppIndexRoute
  '/matrix/data/$dataId': typeof MatrixDataDataIdRoute
  '/matrix/data': typeof MatrixDataIndexRoute
}

export interface FileRoutesByTo {
  '/matrix': typeof MatrixRouteRouteWithChildren
  '/matrix/fields': typeof MatrixFieldsRoute
  '/': typeof AppIndexRoute
  '/matrix/data/$dataId': typeof MatrixDataDataIdRoute
  '/matrix/data': typeof MatrixDataIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/matrix': typeof MatrixRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/matrix/fields': typeof MatrixFieldsRoute
  '/_app/': typeof AppIndexRoute
  '/matrix/data/$dataId': typeof MatrixDataDataIdRoute
  '/matrix/data/': typeof MatrixDataIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/matrix'
    | ''
    | '/matrix/fields'
    | '/'
    | '/matrix/data/$dataId'
    | '/matrix/data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/matrix'
    | '/matrix/fields'
    | '/'
    | '/matrix/data/$dataId'
    | '/matrix/data'
  id:
    | '__root__'
    | '/matrix'
    | '/_app'
    | '/matrix/fields'
    | '/_app/'
    | '/matrix/data/$dataId'
    | '/matrix/data/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MatrixRouteRoute: typeof MatrixRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MatrixRouteRoute: MatrixRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/matrix",
        "/_app"
      ]
    },
    "/matrix": {
      "filePath": "matrix/route.tsx",
      "children": [
        "/matrix/fields",
        "/matrix/data/$dataId",
        "/matrix/data/"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/"
      ]
    },
    "/matrix/fields": {
      "filePath": "matrix/fields.tsx",
      "parent": "/matrix"
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    },
    "/matrix/data/$dataId": {
      "filePath": "matrix/data.$dataId.tsx",
      "parent": "/matrix"
    },
    "/matrix/data/": {
      "filePath": "matrix/data.index.tsx",
      "parent": "/matrix"
    }
  }
}
ROUTE_MANIFEST_END */
